spring:
  mvc:
  messages:
    basename: "i18n.login"
  gson:
    date-format: "yyyy-MM-dd"
  datasource:
    username: root
    password: "123"
    url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
# 整合mybatis
mybatis:
#  type-aliases-package: com.wyb.springboot03web.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml